server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进eureka的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guantongxue/SpringCloudConfig #gitub仓库的地址
          search-paths:
            #搜索目录
            - SpringCloudConfig
      #读取分支
      label: master
  rabbitmq:
    host: 192.168.35.128
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka



#rabbitmq相关配置，暴露bus刷新配置端点
management:
  endpoints: #暴露bus刷新配置的端点
    web:
      exposure:
        include: bus-refresh

