server:
  port: 3344
spring:
  application:
    name: cloud-config-center #注册进eureka的微服务名
  cloud:
    config:
      server:
        git:
          uri: https://github.com/guantongxue/SpringCloudConfig #gitub仓库的地址
          search-paths:
            #搜索目录
            - SpringCloudConfig
      #读取分支
      label: master
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka

