server:
  port: 80

eureka:
  client:
#    是否将自己注册进eureka
    register-with-eureka: false
    #是否从EurekaServer抓取已有的注册信息,单机无所谓,集群必须设置为true配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
ribbon:
#  建立连接所用时间，适用于网络正常的情况下，两端连接所用的时间
  ReadTimeout: 5000
#建立连接后从服务器读取到可用资源的时间
  ConnectTimeout: 5000
#spring:
#  application:
#    name: cloud-order-service

logging:
  level:
    #feign日志以什么级别监控哪个接口
    com.minjiang.springcloud.service.PaymentFeignService: debug
